apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
  labels:
    app.kubernetes.io/instance: cd-pipeline
spec:
  params:
    - name: APP
      type: string
    - name: MESSAGE
      type: string
    - name: APP_REPO
      type: string
    - name: APP_REVISION
      type: string
    - name: IMAGE
      type: string
    - name: IMAGE_VERSION
      type: string
    - name: DEPLOY_REPO
      type: string
    - name: DEPLOY_OWNER
      type: string
    - name: DEPLOY_NAME
      type: string
    - name: ENV
      type: string
  # workspaces: {}
  tasks:
# ------------ UNIT TEST ------------ #
    - name: unit-test
      taskRef:
        kind: Task
        name: mock
      params:
        - name: MOCK_MSG
          value: unit-test-mock